kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cassandra
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: dse-gke-cluster
  serverType: dse
  serverVersion: "6.8.19"
  dseWorkloads:
    searchEnabled: true
    graphEnabled: true
  managementApiAuth:
    insecure: {}
  size: 3
  racks:
    - name: rack1
    - name: rack2
    - name: rack3
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: cassandra
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  config:
    cassandra-yaml:
      num_tokens: 8
      authenticator: com.datastax.bdp.cassandra.auth.DseAuthenticator
      authorizer: com.datastax.bdp.cassandra.auth.DseAuthorizer
      role_manager: com.datastax.bdp.cassandra.auth.DseRoleManager
    dse-yaml:
      authorization_options:
        enabled: true
      authentication_options:
        enabled: true
        default_scheme: internal
    jvm-server-options:
      initial_heap_size: "2G"
      max_heap_size: "2G"
      additional-jvm-opts:
        - "-Ddse.system_distributed_replication_dc_names=dc1"
        - "-Ddse.system_distributed_replication_per_dc=3"
